"""
explainer_agent.py
--------------------
LLM agent: takes the raw risk evidence for a case (graph signals +
rule-based signals) and turns it into a plain-language explanation
that a non-technical accused party could read on appeal.

This satisfies the Auditability guardrail directly -- the explanation
gets written back into fraud_cases.explanation and logged as an
audit_logs event.
"""

import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from llm import call_llm
from database import get_case, update_case, append_audit_log, init_db, get_cases_needing_review

SYSTEM_INSTRUCTION = """You are a fraud-case explainer for an e-commerce trust and safety system.

You will be given evidence about why a seller's account was flagged.
Write a SHORT plain-language explanation (3-5 sentences max) that:
- A non-technical accused seller could read and understand on appeal
- States the specific evidence factually, without accusing the seller
  of guilt (they may be innocent -- this is a flag, not a verdict)
- Avoids jargon like "graph_risk_score" or "shared_attr_ratio" --
  translate these into plain English (e.g. "linked to other accounts
  through shared device or address information")
- Ends with what the seller can do next (verify identity / provide
  documentation / await review)

Do not invent evidence that wasn't given to you."""


def build_prompt(case: dict) -> str:
    return f"""Case evidence:
- Seller ID: {case['seller_id']}
- Final risk score: {case['final_risk_score']} (scale 0-1)
- Risk tier: {case['tier']}

Write the plain-language explanation now."""


def explain_case(case_id: int) -> str:
    """
    Fetches a case, generates a plain-language explanation via LLM,
    writes it back to the case, and logs the audit event.
    Returns the explanation text.
    """
    case = get_case(case_id)
    if case is None:
        raise ValueError(f"No case found with case_id={case_id}")

    prompt = build_prompt(case)
    explanation = call_llm(prompt, system_instruction=SYSTEM_INSTRUCTION)

    update_case(case_id, explanation=explanation)
    append_audit_log(
        case_id,
        event_type="explanation_generated",
        details=f"Explanation generated by explainer_agent: {explanation[:80]}..."
    )

    return explanation


def run_for_all_pending():
    """
    Runs explain_case() for every case that needs agent review and
    doesn't already have an explanation. This is the batch entry
    point you'll call from main.py.
    """
    init_db()
    cases = get_cases_needing_review()
    results = []

    for case in cases:
        if case.get("explanation"):
            continue  # already explained, skip
        explanation = explain_case(case["case_id"])
        results.append((case["case_id"], case["seller_id"], explanation))

    return results


if __name__ == "__main__":
    results = run_for_all_pending()
    for case_id, seller_id, explanation in results:
        print(f"\n--- Case {case_id} | Seller {seller_id} ---")
        print(explanation)